
sei0530: sei0530.hpp sei0530.cpp sei0530_sample.cpp
	g++ -c -std=c++11 -o sei0530_sample sei0530_sample.cpp 2> error.txt
	g++ -c -std=c++11 -o sei0530.o sei0530.cpp 2> error.txt
	g++ sei0530.o sei0530_sample.o -o sei0530